### ISSUE TITLE
Extract field for custom parameters

### ISSUE THREAD

**Issue by iainelder** [iainelder/security-hub-controls#4]
The main table added a column called "Supports custom parameters".

[The latest dump failed because of it](https://github.com/iainelder/security-hub-controls/actions/runs/7001002456/job/19042469691).

Use the Python debugger to reproduce it locally.

```console
python3 -m pdb ./dump-controls 
```

```text
> /tmp/dir.NAz/security-hub-controls/dump-controls(3)<module>()
-> """
(Pdb) c
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/pdb.py", line 1705, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.8/pdb.py", line 1573, in _runscript
    self.run(statement)
  File "/usr/lib/python3.8/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/tmp/dir.NAz/security-hub-controls/dump-controls", line 3, in <module>
    """
  File "/tmp/dir.NAz/security-hub-controls/dump-controls", line 32, in main
    controls = get_available_controls()
  File "/tmp/dir.NAz/security-hub-controls/dump-controls", line 40, in get_available_controls
    return parse_controls(markup)
  File "/tmp/dir.NAz/security-hub-controls/dump-controls", line 48, in parse_controls
    check_header(document)
  File "/tmp/dir.NAz/security-hub-controls/dump-controls", line 64, in check_header
    assert header_texts == expected
AssertionError
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /tmp/dir.NAz/security-hub-controls/dump-controls(64)check_header()
-> assert header_texts == expected
```

```text
(Pdb) expected
['Security control ID', 'Security control title', 'Applicable standards', 'Severity', 'Schedule type']
(Pdb) header_texts
['Security control ID', 'Security control title', 'Applicable standards', 'Severity', 'Supports custom parameters', 'Schedule type']
```

**Comment by iainelder** [comment]
Add SupportsCustomParameters column to dump in 8bea7a6cfd093b0c874386c4e961a1fca048d276.
